name: "Terraform EKS Deployment"

on:
  workflow_dispatch:

jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ec2_keypair_public_key: ${{ secrets.EC2_KEYPAIR_PUBLIC_KEY }}
      TF_VAR_aws_auth_role_arn: ${{ secrets.AWS_AUTH_ROLE_ARN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: ./eks-iac-terraform/eks

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./eks-iac-terraform/eks

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        working-directory: ./eks-iac-terraform/eks

  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main'
    environment: Dev  # This will now wait for approval

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ec2_keypair_public_key: ${{ secrets.EC2_KEYPAIR_PUBLIC_KEY }}
      TF_VAR_aws_auth_role_arn: ${{ secrets.AWS_AUTH_ROLE_ARN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      - name: Terraform Init
        run: terraform init
        working-directory: ./eks-iac-terraform/eks

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./eks-iac-terraform/eks

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        working-directory: ./eks-iac-terraform/eks

      - name: Terraform Apply
        run: terraform destroy -auto-approve 
        working-directory: ./eks-iac-terraform/eks