name: "Terraform VPC Deployment"

on:
  workflow_dispatch:

jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: ./vpc

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./vpc

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./vpc

  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main'
    environment: Dev  # This will now wait for approval

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
      - name: Terraform Init
        run: terraform init
        working-directory: ./vpc

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./vpc

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./vpc

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./vpc